# Assignment 3

-----
## Task1
-----

### 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [96]:
def division(num,den):
    try:
        result=num/den
    except ZeroDivisionError:
        print("Zero Division error occured")
        result='infinity'
    return result

In [100]:
division(5,0)

Zero Division error occured


'infinity'

In [101]:
5/0

ZeroDivisionError: division by zero

-----

### 2.Implement a Python program to generate all sentences where subject is in
### ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"] <br>
verbs=["play","watch"]<br>
objects=["Baseball","Cricket"]<br>

Output should come as below:

Americans play Baseball.<br>
Americans play Cricket.<br>
Americans watch Baseball.<br>
Americans watch Cricket.<br>
Indians play Baseball.<br>
Indians play Cricket.<br>
Indians watch Baseball.<br>
Indians watch Cricket.

In [3]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
for i in subjects:
    for j in verbs:
        for k in objects:
            print (i,j,k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


-----
## Task2
-----

### 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [86]:
def Vandermonde(my_list,n,increasing):
    import numpy as np
    if increasing == True:
        output = np.array([[i**j for j in range(n)] for i in my_list])
        print(output)
    else:
        output=np.array([[i**j for j in range((n-1),-1,-1)] for i in my_list])
        print(output)

In [94]:
Vandermonde([1,2,3,4],4,False)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [92]:
Vandermonde([1,2,3,4],4,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
