# Numpy Assignment

### 1.Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 
### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [1]:
def Vandermonde(my_list,n,increasing):
    import numpy as np
    if increasing == True:
        output = np.array([[i**j for j in range(n)] for i in my_list])
        print(output)
    else:
        output=np.array([[i**j for j in range((n-1),-1,-1)] for i in my_list])
        print(output)

In [2]:
Vandermonde([1,2,3,4],4,False)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [3]:
Vandermonde([1,2,3,4],4,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


##### 2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
##### the given sequence is defined as follows:
##### The moving average sequence has n-k+1 elements as shown below.
##### The moving averages with k=4 of a ten-value sequence (n=10) is shown below
##### i 1 2 3 4 5 6 7 8 9 10
##### ===== == == == == == == == == == ==
##### Input 10 20 30 40 50 60 70 80 90 100
##### y1 25 = (10+20+30+40)/4
##### y2 35 = (20+30+40+50)/4
##### y3 45 = (30+40+50+60)/4
##### y4 55 = (40+50+60+70)/4
##### y5 65 = (50+60+70+80)/4
##### y6 75 = (60+70+80+90)/4
##### y7 85 = (70+80+90+100)/4
##### Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [4]:
def movingaverage(my_list,k):
  import numpy as np
  input=np.array(my_list)
  n=len(input)
  i=0
  k=4
  for i in range(n-k+1):
    total=input[i:(i+k)].sum()
    average=total/k
    print(average) 

In [5]:
movingaverage([10,20,30,40,50,60,70,80,90,100],4)

25.0
35.0
45.0
55.0
65.0
75.0
85.0


In [6]:
movingaverage([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

4.25
5.5
6.75
7.75
23.5
39.5
57.25
79.25
88.0
107.5
